name: Realworld API Tests

on: [push]

jobs:
  pre-commit:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Execute Static Tests
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files
  unit-tests:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Execute Unit Tests
        run: docker-compose up --build unit-tests
  integration-tests:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Execute Integration Tests
        run: docker-compose up --build integration-tests
